"""drop ticker column from watchlist

Revision ID: 066e1907d334
Revises: fa84b11335af
Create Date: 2025-10-07 18:25:57.471730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066e1907d334'
down_revision: Union[str, Sequence[str], None] = 'fa84b11335af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_ticker'), table_name='watchlist')
    op.drop_column('watchlist', 'ticker')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_watchlist_ticker'), 'watchlist', ['ticker'], unique=False)
    # ### end Alembic commands ###
